# Generated by Django 5.2.1 on 2025-05-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_chatnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatnotification",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
