# Generated by Django 5.2.1 on 2025-05-25 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_coursematerial"),
        ("dashboard", "0003_remove_notification_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
    ]
