# Generated by Django 5.2.1 on 2025-07-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assignment_submission", "Assignment Submission"),
                    ("material_upload", "Material Upload"),
                    ("chat", "Chat"),
                    ("course_drop", "Course Drop"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
