# Generated by Django 5.2.1 on 2025-05-23 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="course",
        ),
    ]
