# Generated by Django 5.2.1 on 2025-07-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_assignmentsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="course_images/"),
        ),
    ]
