# Generated by Django 5.2.1 on 2025-05-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_privatemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemessage",
            name="room_name",
            field=models.CharField(default="private_chat_placeholder", max_length=100),
            preserve_default=False,
        ),
    ]
